# Sets the DOTFILES_PATH environment variable
source ~/.zsh/path-finder.zsh

# Named Directories — https://zsh.sourceforge.io/Guide/zshguide02.html#l20
export dotfiles=$DOTFILES_PATH
export dd=~/Library/Developer/Xcode/DerivedData

# bat
export BAT_THEME="base16"

# editor
export EDITOR='vim'
# keep emacs cli bindings even though EDITOR is vim
# https://unix.stackexchange.com/questions/197839/why-does-exporting-vim-as-editor-in-zsh-disable-keyboard-shortcuts
bindkey -e

# fzf
export FZF_COMPLETION_TRIGGER=','
export FZF_COMPLETION_OPTS='--border'

# homebrew
export HOMEBREW_BUNDLE_NO_LOCK=1

# workenv.zsh
[[ -f ~/.work/workenv.zsh ]] && source ~/.work/workenv.zsh
