# Sets the DOTFILES_PATH environment variable
source ~/.zsh/dotfiles-path-finder.zsh

# Named Directories — https://zsh.sourceforge.io/Guide/zshguide02.html#l20
export dotfiles=$DOTFILES_PATH
export dd=~/Library/Developer/Xcode/DerivedData

# bat
export BAT_THEME="base16"

# fzf
export FZF_COMPLETION_TRIGGER=','
export FZF_COMPLETION_OPTS='--border'

# homebrew
export HOMEBREW_BUNDLE_NO_LOCK=1

# workenv.zsh
[[ -f ~/.work/workenv.zsh ]] && source ~/.work/workenv.zsh

